services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dr-koala-api
    ports:
      - "7086:7086"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      APP_NAME: "Dr. Koala"
      IS_DEVELOPMENT: true
      LOG_LEVEL: INFO
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: dr_koala
      DB_USER: postgres
      DB_PASSWORD: postgres
      SHOULD_RESET_DATABASE: true
