services:
  postgresql:
    image: "postgres:17"
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dr-koala-api
    ports:
      - "7086:7086"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      APP_NAME: "Dr. Koala"
      IS_DEVELOPMENT: false
      LOG_LEVEL: INFO
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      SHOULD_RESET_DATABASE: false
      XAI_API_KEY: ${XAI_API_KEY}
      BRAVE_SEARCH_API_KEY: ${BRAVE_SEARCH_API_KEY}
    restart: unless-stopped

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:7086}
    container_name: dr-koala-client
    ports:
      - "3076:3076"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres-data:

name: dr-koala
